repos:
-   repo: local
    hooks:
    -   id: nocommit
        name: NOCOMMIT check
        entry: NOCOMMIT
        language: pygrep
        exclude: .pre-commit-config.yaml
        types: [text]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-json
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ["--maxkb=10000"]
    -   id: check-case-conflict

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.7
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies:
            - attrs
            - types-PyYAML
            - types-cachetools
        args:
        - --ignore-missing-imports
        - --namespace-packages
        - --explicit-package-bases

-   repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        #name: pytest
        #entry: .venv/bin/pytest
        #language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true

# -   repo: "https://github.com/tweag/FawltyDeps.git"
#     rev: main # v0.18.0
#     hooks:
#       - id: check-undeclared
#       - id: check-unused
