[project]
name = "firm"
version = "0.1.0"
description = "Federated Information Resource Manager (FIRM)"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.14"
authors = [
    { name = "Steve Bate", email = "svc-github@stevebate.net" }
]
dependencies = [
  "cryptography>=43.0.0,<44.0.0",
  "bcrypt>=4.2.0,<5.0.0",
  "uvicorn>=0.30.6,<0.31.0",
  "colorama>=0.4.6,<0.5.0",
  "coloredlogs>=15.0.1,<16.0.0",
  "python-dotenv>=1.0.1,<2.0.0",
  "pyyaml>=6.0.2,<7.0.0",
  "dacite>=1.8.1,<2.0.0",
  "python-mimeparse>=2.0.0,<3.0.0",
  "jinja2>=3.1.4,<4.0.0",
  "oxrdflib>=0.3.7,<0.4.0",
  "python-multipart>=0.0.20,<0.0.21",
  "bleach>=6.2.0,<7.0.0",
  "fastapi>=0.135",
  "httpx-cache>=0.13.0",
  "pyld>=2.0.4",
  "rdflib>=7.6.0",
  "rdflib-endpoint>=0.6.1",
  "rfc3987>=1.3.8",
  "jsonschema>=4.26.0",
  "aiosqlite>=0.22.1",
  "cachetools-async>=0.0.5",
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "pytest-httpx>=0.30.0,<0.31.0",
]

[project.scripts]
firm = "firm.server.cli.main:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = 'function'
markers = [
  "skip_unless: mark test to run only if condition is met",
]

[tool.ruff]
line-length = 100

[tool.black]
line-length = 100

[tool.fawltydeps]
ignore_undeclared = ["pytest"]
ignore_unused = ["pytest-asyncio", "pre-commit", "pytest-cov", "pytest-assume"]
