[project]
name = "firm"
version = "0.1.0"
description = "Federated Information Resource Manager (FIRM)"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.14"
authors = [
    { name = "Steve Bate", email = "svc-github@stevebate.net" }
]
dependencies = [
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = 'function'

[tool.black]
line-length = 100
