name: Check and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Lint with ruff
      run: hatch fmt --check

    - name: Lint with mypy
      run: |
        hatch run mypy --install-types --non-interactive da_dedup scripts

    - name: Test with pytest
      run: hatch test
